### PR TITLE
Fo dicom 4

### PR DESCRIPTION
**Pull request by shelbypereira**
Added 2 unit tests and fixed the isseus found with the migration.  I also tested from the Wadojs tool and I am able to Stow and then use Qido and Wado to find/get  things look much better in this version.  At the moment I have nothing more to added for the migration,  all the unit tests pass.  Minor improvements were made to the setup of the pagination tests to make them more robust.

### CODE REVIEW

**Comment by shelbypereira** [comment]
added a web.config attribute to work around the UID issue for some WADO requests

**Comment by shelbypereira** [comment]
HEllo,  note that my last  push to the branch which adds nLog support was not intentional.  Feel free to remove it,  I did not realize my local repository was bound to your branch (and I did not realize that I actually could push directly to your branch).

I am currently trying to make DICOMCloud work with Cornerstone and I am seeing some issues.  I need  much better logging support, the existing  Microsoft Diagnostic Tracing is  insufficient, so I went forward and included nLog.  I also log all incoming requests using an attribute (to identify the controller/Action being called).  I also log all incoming requests in a small module.

I will avoid comitting here directly in the future anything tha is not relevant for 4.x migration.

**Comment by shelbypereira** [comment]
Actually from what I see my commits to my fork are being sent here automatically I guess due to the pull request.  I am not an expert on Github,  in the past I was always using Team Foundation Server...

I will make a new branch in my fork, and possibly if your interested in the logging I am adding,  I can make a new pull request.

**Comment by Zaid-Safadi** [comment]
merge changes

**Comment by Zaid-Safadi** [comment]
Hi @shelbypereira I've finally got to merging this into dev after validating resolving the issues that came with the updated fo-dicom. Thank you for the effort on this.

I don't think I've seen your event logging updates in this branch but I agree that this is one of the things that should be improved in DICOMcloud. You are more than welcome to create a PR with improved logging.

Thanks again for your effor @shelbypereira

**Pull request closed without merging**
